ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:01:13,195
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=' from '='
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:01:13,219
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=' from '='
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:01:13,232
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=' from '='
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188082 2022-01-10 14:01:13,237
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188082 2022-01-10 14:01:13,242
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188082 2022-01-10 14:01:13,246
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:04:31,519
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=' from '='
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188388 2022-01-10 14:04:31,524
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:04:44,490
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' = 0' from 'case.case_description|length = 0'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 181195 2022-01-10 14:04:44,493
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:04:45,507
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' = 0' from 'case.case_description|length = 0'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 181195 2022-01-10 14:04:45,510
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:05:27,725
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' = 0' from 'case.case_description|length = 0'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 181205 2022-01-10 14:05:27,728
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:05:28,686
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 979, in do_if
    nodelist = parser.parse(('endif',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' = 0' from 'case.case_description|length = 0'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 181205 2022-01-10 14:05:28,691
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:06:32,642
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'case.case_text|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from 'case.case_text|'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188942 2022-01-10 14:06:32,646
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:07:04,507
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '<0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '<0' from '<0'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188113 2022-01-10 14:07:04,510
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:11:35,675
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'case.case_result|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from 'case.case_result|'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 189091 2022-01-10 14:11:35,678
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:11:41,389
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'case.case_result|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from 'case.case_result|'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 189091 2022-01-10 14:11:41,393
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:11:43,285
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'case.case_result|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from 'case.case_result|'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 189091 2022-01-10 14:11:43,290
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:11:48,678
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from '|'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 188248 2022-01-10 14:11:48,683
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:11:54,426
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 193, in parse
    raise self.error_class("Unused '%s' at end of if expression." %
django.template.exceptions.TemplateSyntaxError: Unused 'case.case_result|length' at end of if expression.
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 162357 2022-01-10 14:11:54,429
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:14:33,540
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'case.exact_data|'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '|' from 'case.exact_data|'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 189311 2022-01-10 14:14:33,544
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:18:37,850
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 483, in parse
    self.unclosed_block_tag(parse_until)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 544, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 21: 'for'. Looking for one of: empty, endfor.
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 164246 2022-01-10 14:18:37,853
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:19:10,750
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 813, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(case)' from 'length(case)'
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 157859 2022-01-10 14:19:10,762
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:20:13,639
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 483, in parse
    self.unclosed_block_tag(parse_until)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 544, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 21: 'for'. Looking for one of: empty, endfor.
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 164253 2022-01-10 14:20:13,643
ERROR django.request Internal Server Error: /analytic/detail/24/ 2022-01-10 14:20:16,690
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\statistica\views.py", line 177, in case_detail
    return render(request, 'statistica/detail_case2.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 483, in parse
    self.unclosed_block_tag(parse_until)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 544, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 21: 'for'. Looking for one of: empty, endfor.
ERROR django.server "GET /analytic/detail/24/ HTTP/1.1" 500 164253 2022-01-10 14:20:16,693
